### ISSUE TITLE
How do i use it？

### ISSUE THREAD

**Issue by guikunchen** [raluca-scona/staticfusion#2]
I had successfully compiled this program and got the dataset from the page provided by the author. But i didn't know how to use them.

I had used ElasticFusion, as shown below
~~~
./ElasticFusion -l dyson_lab.klg
~~~
Could you give me some way to use StaticFusion?

Looking forward to your help， thanks！

**Comment by raluca-scona** [comment]
Hi, sorry for the late reply, I was away.

To run the program on the two provided image sequences, you have to edit the StaticFusion-imagesequenceassoc.cpp file. Specifically, replace the `std::string dir` variable with the path to where you store your sequences.

If you want to test the method on the TUM dataset, modify the StaticFusion-datasets.cpp file by setting the `dataset.filename` variable to the path where you store your sequences.
